from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def open_source_strategy_catalog() -> dict[str, Any]:
    return {
        "checked_at": datetime.now(timezone.utc).isoformat(),
        "mode": "research_registry",
        "rule": "External repos are treated as design references until they pass paper-trade and risk review inside this system.",
        "repos": [
            {
                "id": "polyliquid",
                "name": "Polymarket Liquidity Rewards Bot",
                "repo_url": "https://github.com/polymarket-liquidity-rewards-bot/polymarket-liquidity-rewards-bot",
                "category": "market_making",
                "fit": "execution_layer_reference",
                "priority": "high",
                "status_here": "research_only",
                "dry_run_friendly": True,
                "why_it_matters": "Useful reference for two-sided quoting, spread control, inventory limits, and rewards-aware market making.",
                "how_to_use_here": "Borrow quote/risk ideas for the future paper OMS. Do not connect wallet execution yet.",
                "risks": ["requires wallet/private key for live use", "maker strategies can hide inventory risk", "rewards harvesting can overfit to fee structure"],
            },
            {
                "id": "polybot",
                "name": "Polybot",
                "repo_url": "https://github.com/ent0n29/polybot",
                "category": "copy_trading_and_research",
                "fit": "ingestion_and_analytics_reference",
                "priority": "high",
                "status_here": "partial_fit",
                "dry_run_friendly": True,
                "why_it_matters": "Strong reference for trade ingestion, trader behavior analysis, replication scoring, and paper-vs-live service boundaries.",
                "how_to_use_here": "Mirror the research and analytics patterns, not the full Java microservice stack.",
                "risks": ["heavier infrastructure footprint", "ClickHouse/Redpanda complexity", "copying traders without attribution and risk filters is fragile"],
            },
            {
                "id": "cloddsbot",
                "name": "CloddsBot",
                "repo_url": "https://github.com/alsk1992/CloddsBot",
                "category": "multi_strategy_prediction_markets",
                "fit": "strategy_ideas_reference",
                "priority": "medium",
                "status_here": "research_only",
                "dry_run_friendly": True,
                "why_it_matters": "Broad strategy surface across Polymarket, Kalshi, Binance, and cross-venue arbitrage.",
                "how_to_use_here": "Use as a strategy catalog source; import ideas selectively into monitor-only gates first.",
                "risks": ["too broad to trust without narrowing scope", "cross-venue execution risk", "AI agent autonomy can hide weak assumptions"],
            },
            {
                "id": "polyweather",
                "name": "PolyWeather",
                "repo_url": "https://github.com/yangyuan-zhen/PolyWeather",
                "category": "event_specific_alpha",
                "fit": "specialist_subagent_reference",
                "priority": "medium",
                "status_here": "research_only",
                "dry_run_friendly": True,
                "why_it_matters": "A good model for event-specific specialist agents where domain data matters more than generic TA.",
                "how_to_use_here": "Use as the blueprint for future weather/event subagents rather than general market predictions.",
                "risks": ["narrow scope", "special data quality issues", "not reusable for broad equities/crypto without domain adaptation"],
            },
            {
                "id": "harrier_toolkit",
                "name": "Harrier OnChain Toolkit",
                "repo_url": "https://github.com/HarrierOnChain",
                "category": "toolkit",
                "fit": "execution_pattern_reference",
                "priority": "medium",
                "status_here": "catalog_only",
                "dry_run_friendly": True,
                "why_it_matters": "Covers copy trading, arbitrage, market making, and alerts in one toolkit family.",
                "how_to_use_here": "Use as a menu of execution patterns, then implement only the patterns that can be justified with our gates.",
                "risks": ["toolkit breadth can obscure weak modules", "live execution assumptions vary by subtool"],
            },
            {
                "id": "tradingagents",
                "name": "TradingAgents",
                "repo_url": "https://github.com/tauricresearch/tradingagents",
                "category": "multi_agent_research",
                "fit": "subagent_architecture_reference",
                "priority": "high",
                "status_here": "already_influencing_design",
                "dry_run_friendly": True,
                "why_it_matters": "Closest match to the research-brain architecture: analyst debate, risk review, and portfolio-level decisioning.",
                "how_to_use_here": "Keep using it as the template for specialist research roles and memory/reflection loops.",
                "risks": ["agent theater without hard gates is dangerous", "LLM reasoning must remain evidence-bound"],
            },
            {
                "id": "tradingview_mcp",
                "name": "TradingView MCP",
                "repo_url": "https://github.com/atilaahmettaner/tradingview-mcp",
                "category": "charting_and_indicator_access",
                "fit": "indicator_source_reference",
                "priority": "high",
                "status_here": "planned",
                "dry_run_friendly": True,
                "why_it_matters": "Candidate path for richer indicator reads and chart-state access without writing everything from scratch.",
                "how_to_use_here": "Use only as a read-only indicator/context source if installed later. Do not treat TradingView output as an execution trigger by itself.",
                "risks": ["third-party MCP reliability", "indicator abundance can create overfit confluence"],
            },
            {
                "id": "sec_edgar_mcp",
                "name": "SEC EDGAR MCP",
                "repo_url": "https://github.com/stefanoamorelli/sec-edgar-mcp",
                "category": "fundamental_filings",
                "fit": "filings_research_reference",
                "priority": "high",
                "status_here": "partially_replaced_by_free_sec_endpoint",
                "dry_run_friendly": True,
                "why_it_matters": "Best path to structured filing analysis once we want deeper fundamentals and filing-aware agents.",
                "how_to_use_here": "Start with the free SEC endpoint now, then add MCP only if we need deeper filing parsing.",
                "risks": ["AGPL/commercial boundary", "filing text analysis can become expensive and noisy if not scoped"],
            },
            {
                "id": "openbb",
                "name": "OpenBB",
                "repo_url": "https://github.com/OpenBB-finance/OpenBB",
                "category": "research_terminal",
                "fit": "data_source_reference",
                "priority": "medium",
                "status_here": "future_optional",
                "dry_run_friendly": True,
                "why_it_matters": "Broad open-source financial data and research surface.",
                "how_to_use_here": "Use as a source of ideas for additional no-key datasets and screeners, not as the primary runtime.",
                "risks": ["large dependency surface", "data-source drift across connectors"],
            },
        ],
        "next_actions": [
            "Keep external bot logic monitor-only until it passes our paper execution and audit standards.",
            "Prefer design extraction over direct repo embedding.",
            "Use SEC + macro + news + microstructure as shared evidence layers across all future strategies.",
        ],
    }
